---
title: 'PSTAT 174 Code'
author: "Yujie Ye"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

Packages used
```{r}
library(MASS)
library(forecast)
library(qpcR)
library(stats)
library(ggplot2)
```

```{r}
#data
setwd("/Users/johnnys/Downloads/PSTAT 174")

frozen = read.table("IPN31152N.csv",
                    sep=",", header=FALSE, skip=1)

fro <- frozen[1:132,]
fro.test <- frozen[133:144,]

#plot original
ice = ts(frozen[,2], start = c(1981,1), end = c(1993,1), frequency = 12)
reg <- lm(V2 ~ as.numeric(1:132), data = fro)
plot(V2 ~ as.numeric(1:132), data = fro); abline(reg)
op = par(mfrow = c(1,2))
ice1 = ts(fro[,2], start = c(1981,1), end = c(1991,12), frequency = 12)
ice1_1 = ts(fro[,2], start = c(0), end = c(131), frequency = 1)
ts.plot(ice1_1, ylab = "index 2017 = 100"); abline(reg,col = "red")
ts.plot(ice1, ylab = "index 2017 = 100")
#histogram / ACF/PACF of original data

op = par(mfrow = c(1,3))
hist(ice1, main = "")
acf(ice1,lag.max = 60,main = "")
pacf(ice1,lag.max = 60,main = "")
```

```{r}
#find lambda to transform (constant variables)
t = 1:length(ice1)
fit = lm(ice1 ~ t)
bcTransform = boxcox(ice1 ~ t,plotit = TRUE)

lambda = bcTransform$x[which(bcTransform$y == max(bcTransform$y))]
ice1.bc = (1/lambda)*(ice1^lambda-1)
ice1.log = log(ice1)
op= par(mfrow=c(2,2))
ts.plot(ice1, main = "Original Times Series")
ts.plot(ice1_1, main = "Original Times Series"); abline(reg,col = "red")
ts.plot(ice1.bc, main = "Box-Cox Transform")
ts.plot(ice1.log, main = "Log Transform")

#Compare before and after log
par(mfrow=c(3,3))
plot.ts(ice1,xlab = "", main = "")
hist(ice1, xlab = "", main="Original data")
qqnorm(ice1, main = "", xlab = "")
qqline(ice1, col = "red")

plot.ts(ice1.log,xlab = "", main = "")
hist(ice1.log, xlab = "", main = "log transformed data")
qqnorm(ice1.log, main = "", xlab = "")
qqline(ice1.log, col = "red")

plot.ts(ice1.bc,xlab = "", main = "")
hist(ice1.bc, xlab = "", main = "Box-Cox transformed data")
qqnorm(ice1.bc, main = "", xlab = "")
qqline(ice1.bc, col = "red")
```

```{r}
# de-seasonal and de-trend
y2 = diff(ice1.log, 12)
y21 = diff(y2, 1)
y211 = diff(y21, 1)
ts.plot(y2, main = "De-seasonalized Time Series",
        ylab = expression(nabla^{12}~Y[t]))
abline(h = 0,lty = 2)

ts.plot(y21,main= "De-trended/seasonalized Time Series",
        ylab = expression(nabla^{12}~nabla~Y[t]))
abline(h = 0,lty = 2)

c(Ut = var(ice1.log),delta_12 = var(y2),delta_1_12 = var(y21)
  ,deta_1_1_12 = var(y211))
#compare acf and pacf
op= par(mfrow=c(2,3))
acf(ice1.log,lag.max = 60,main = expression(ln(U[t])))
acf(y2,lag.max = 60,main = expression(nabla[12]~~ln(U[t])))
acf(y21,lag.max = 60,main = expression(nabla[12]~nabla[1]~~ln(U[t])))
pacf(ice1.log,lag.max = 60,main = "")
pacf(y2,lag.max = 60,main = "")
pacf(y21,lag.max = 60,main = "")

#ACF and PACF of de-trend&season
decomp <- decompose(ts(as.ts(ice1.bc), 
                       start=c(1981,1), end=c(1991,12), frequency = 12))
plot(decomp)
op= par(mfrow=c(1,2))
acf(y21,lag.max = 60,main = "ACF of the log(U_t) differenced at lags 12 and 1")
pacf(y21,lag.max = 60,main = "PACF of the log(U_t) differenced at lags 12 and 1")
```

```{r}
# D = 1; s = 12; d = 1; Q = 1; P = 0 or 1 or 2; q = 1; p = 1 or 0(tail off)
fit_1 <- arima(ice1.log, order = c(0,1,1), seasonal = list(order = c(0,1,1))
               ,method = "ML")
fit_2 <- arima(ice1.log, order = c(1,1,1), seasonal = list(order = c(0,1,1))
               ,method = "ML")
fit_3 <- arima(ice1.log, order = c(0,1,1), seasonal = list(order = c(1,1,1))
               ,method = "ML")
fit_4 <- arima(ice1.log, order = c(1,1,1), seasonal = list(order = c(1,1,1))
               ,method = "ML")
fit_5 <- arima(ice1.log, order = c(0,1,1), seasonal = list(order = c(2,1,1))
               ,method = "ML")
fit_6 <- arima(ice1.log, order = c(1,1,1), seasonal = list(order = c(2,1,1))
               ,method = "ML")

fit_1;fit_2;fit_3;fit_4;fit_5;fit_6
c(fit_1 = AICc(fit_1),fit_2 = AICc(fit_2),fit_3 = AICc(fit_3),
  fit_4 = AICc(fit_4),fit_5 = AICc(fit_5),fit_6 = AICc(fit_6))
fit_1
fit_2

fit_2_2 <-arima(ice1.log, order = c(1,1,1), seasonal = list(order = c(0,1,1)), 
                fixed = c(0,0,NA)
               ,method = "ML")

c(fit_1 = AICc(fit_1),fit_2_2 = AICc(fit_2_2))
```





$$
\nabla_{1}\nabla_{12}ln(U_t): X_t = (1-0.4049_{0.0780}B)(1-0.8213_{(0.1183)}B^{12})Z_t\\
\hat{\sigma_Z}^2 = 0.0008616 
$$
```{r}
#check Invertible
polyroot(c(1,-0.4049))
polyroot(c(1,-0.8213))
```
MA: stationary


```{r}
# Diagnose
modelA <- arima(ice1.log, order = c(0,1,1), seasonal = list(order = c(0,1,1))
               ,method = "ML")

op= par(mfrow=c(1,3))
resA <- residuals(modelA)
plot.ts(resA, xlab = ""); abline(h=mean(resA),col = "red")
fitt <- lm(resA ~ seq(1981,1992,1/12)[1:length(resA)]); abline(fitt,col="blue")

hist(resA, density = 20, breaks = 20, col = "blue",main ="", xlab = "", prob = TRUE);

qqnorm(resA, main = ""); qqline(resA, col="blue")
######
op= par(mfrow=c(1,2))
acf(resA, lag.max = 40)
pacf(resA, lag.max = 40)

######

```

```{r}
#Tests
shapiro.test(resA)
Box.test(resA, lag = 11, type = c("Box-Pierce"), fitdf = 2)
Box.test(resA, lag = 11, type = c("Ljung-Box"), fitdf = 2)
ar(resA, aic = TRUE, order.max = NULL, method = c("yule-walker"))
Box.test((resA)^2, lag = 11, type = c("Ljung-Box"), fitdf = 0)
```



Forecast
```{r}
op= par(mfrow=c(1,2))
fit_1_1 <- arima(ice1.log, order = c(0,1,1), seasonal = list(order = c(0,1,1),period=12)
                 ,method = "ML")
# Create confidence interval
pred.tr <- predict(fit_1_1, n.ahead = 12)
U.tr = pred.tr$pred + 2*pred.tr$se
L.tr = pred.tr$pred - 2*pred.tr$se
# Forecast on original data
ts.plot(ice1.log, xlim = c(1981,1993), xlab="",
        ylim = c(min(ice1.log), max(U.tr))) 
lines(U.tr, col = "blue", lty = "dashed")
lines(L.tr, col = "blue", lty = "dashed") 
points(pred.tr$pred,col = "red", pch = 1) 
legend("bottomright", c("Prediction","95% C.I."),
       fill = c("red", "blue"), cex = 1.25)

pred.orig <- exp(pred.tr$pred)
U = exp(U.tr)
L = exp(L.tr)
ts.plot(ice1, xlim= c(1981,1993), ylim= c(min(ice1), max(U)))
lines(U, col="blue", lty="dashed")
lines(L, col="blue", lty="dashed")
points(pred.orig,col = "red", pch = 1)
legend("bottomright", c("Prediction","95% C.I."),
fill = c("red", "blue"), cex = 1)
```

Forecast with test data
```{r}
pred.orig <- exp(pred.tr$pred)
ts.plot(ice, xlim= c(1981,1993),ylim=c(80,300))
lines(U, col="blue", lty="dashed")
lines(L, col="blue", lty="dashed")
points(pred.orig,col = "red", pch = 1)
points(ice1,col = "black", pch = 20)
legend("bottomright", c("Prediction","95% C.I.","original data"),
       fill = c("red", "blue","black"), cex = 0.7)
```
Zoom in: Forecast on original data and Forecast on original data with actual values
```{r}
op= par(mfrow=c(1,2))
pred.orig <- exp(pred.tr$pred)
U = exp(U.tr)
L = exp(L.tr)
ts.plot(ice1, xlim= c(1990,1993), ylim= c(min(ice1), max(U)))
lines(U, col="blue", lty="dashed")
lines(L, col="blue", lty="dashed")
points(pred.orig,col = "red", pch = 1)
legend("bottomright", c("Prediction","95% C.I."),
fill = c("red", "blue"), cex = 0.8)

pred.orig <- exp(pred.tr$pred)
ts.plot(ice, xlim= c(1990,1993),ylim=c(90,270))
lines(U, col="blue", lty="dashed")
lines(L, col="blue", lty="dashed")
points(pred.orig,col = "red", pch = 1)
points(ice1,col = "black", pch = 20)
legend("bottomright", c("Prediction","95% C.I.","original data"),
       fill = c("red", "blue","black"), cex = 0.7)
```

